/*
 * generated by Xtext 2.9.2
 */
package de.htwg.konstanz.mgse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LocationDistanceDslStandaloneSetup extends LocationDistanceDslStandaloneSetupGenerated {

	def static void doSetup() {
		new LocationDistanceDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
