/*
 * generated by Xtext 2.9.2
 */
package de.htwg.konstanz.mgse


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LocationDistanceDslRuntimeModule extends AbstractLocationDistanceDslRuntimeModule {
}
