grammar de.htwg.konstanz.mgse.LocationDistanceDsl with org.eclipse.xtext.common.Terminals

generate locationDistanceDsl "http://www.htwg.de/konstanz/mgse/LocationDistanceDsl"

Land: 'Land ' name=ID trips+=Trip+ ';' ;

Trip: 'Trip' name=ID locations+=Location+;

Location: 'Location' name=ID 'mit' geokoordinaten=Geokoordinaten;

terminal DOUBLE:
	'-'? INT? '.' INT;

Geokoordinaten: 'Geokoordinaten' name=ID '('x=DOUBLE','y=DOUBLE')';