/*
 * generated by Xtext 2.9.2
 */
package de.htwg.konstanz.mgse.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class LocationDistanceDslScopeProvider extends AbstractLocationDistanceDslScopeProvider {

}
